function getDemoContacts() {
  return [
    {
      id: 'demo-1',
      firstName: 'Sarah',
      lastName: 'Chen',
      fullName: 'Sarah Chen',
      role: 'VP of Sales',
      email: 'sarah.chen@techvision.com',
      phone: '+1 (415) 555-0192',
      leadStatus: 'NEW',
      company: {
        id: 'demo-co-1',
        name: 'TechVision Inc.',
        industry: 'Software',
        revenue: '10000000',
        employees: '150',
        description: 'B2B SaaS platform for enterprise data analytics',
        website: 'techvision.com',
        location: 'San Francisco, CA',
      },
    },
    {
      id: 'demo-2',
      firstName: 'Marcus',
      lastName: 'Rodriguez',
      fullName: 'Marcus Rodriguez',
      role: 'Head of Revenue Operations',
      email: 'm.rodriguez@scaleup.io',
      phone: '+1 (312) 555-0847',
      leadStatus: 'NEW',
      company: {
        id: 'demo-co-2',
        name: 'ScaleUp.io',
        industry: 'Marketing Technology',
        revenue: '5000000',
        employees: '80',
        description: 'Growth marketing automation for e-commerce brands',
        website: 'scaleup.io',
        location: 'Chicago, IL',
      },
    },
    {
      id: 'demo-3',
      firstName: 'Jennifer',
      lastName: 'Walsh',
      fullName: 'Jennifer Walsh',
      role: 'Chief Revenue Officer',
      email: 'jwalsh@nexusretail.com',
      phone: '+1 (212) 555-0334',
      leadStatus: 'ATTEMPTED',
      company: {
        id: 'demo-co-3',
        name: 'Nexus Retail Group',
        industry: 'Retail Technology',
        revenue: '50000000',
        employees: '500',
        description: 'Omnichannel retail solutions for mid-market retailers',
        website: 'nexusretail.com',
        location: 'New York, NY',
      },
    },
    {
      id: 'demo-4',
      firstName: 'David',
      lastName: 'Kim',
      fullName: 'David Kim',
      role: 'Director of Sales Development',
      email: 'david.kim@fintrack.co',
      phone: '+1 (650) 555-0621',
      leadStatus: 'NEW',
      company: {
        id: 'demo-co-4',
        name: 'FinTrack Co.',
        industry: 'Financial Technology',
        revenue: '25000000',
        employees: '200',
        description: 'Real-time financial analytics and reporting for CFOs',
        website: 'fintrack.co',
        location: 'Palo Alto, CA',
      },
    },
    {
      id: 'demo-5',
      firstName: 'Amanda',
      lastName: 'Foster',
      fullName: 'Amanda Foster',
      role: 'VP of Business Development',
      email: 'afoster@healthpulse.com',
      phone: '+1 (617) 555-0983',
      leadStatus: 'NEW',
      company: {
        id: 'demo-co-5',
        name: 'HealthPulse Systems',
        industry: 'Healthcare Technology',
        revenue: '15000000',
        employees: '120',
        description: 'Patient engagement and telehealth platform for clinics',
        website: 'healthpulse.com',
        location: 'Boston, MA',
      },
    },
  ];
}

module.exports = { getDemoContacts };
